# Generated by Django 2.1 on 2022-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='our_goal',
            field=models.TextField(default='Please fill here'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='our_goal_title',
            field=models.TextField(default='Affordability'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='our_mission',
            field=models.TextField(default='Please fill here'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='our_mission_title',
            field=models.TextField(default='Reduced Cost'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='our_vision',
            field=models.TextField(default='Please fill here'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='our_vision_title',
            field=models.TextField(default='Vision'),
        ),
    ]
