# Generated by Django 2.2.5 on 2019-10-02 17:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_portfoliopage_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='baths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='beds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='floors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='garage',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='lifts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='mosque',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='project_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
