# Generated by Django 2.1 on 2019-10-14 09:52

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191009_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_title',
            field=models.TextField(default='Affordable, Quality Housing'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='value_proposition',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
