# Generated by Django 2.1 on 2019-10-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191014_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='approach_title',
            new_name='approach',
        ),
    ]
