# Generated by Django 2.1 on 2019-10-14 14:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0010_auto_20191014_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('Squarefeet', models.TextField(blank=True)),
                ('beds', models.TextField(blank=True)),
                ('lifts', models.BooleanField(default=False)),
                ('baths', models.TextField(blank=True)),
                ('garage', models.TextField(default=True)),
                ('floors', models.TextField(blank=True)),
                ('project_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='Squarefeet',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='lifts',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='project_image',
        ),
        migrations.AlterField(
            model_name='portfolio_images',
            name='Page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='home.ProjectsPage'),
        ),
    ]
