# Generated by Django 2.1 on 2019-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191014_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
