# Generated by Django 2.1 on 2022-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_projectspage_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='projectspage',
            name='status',
            field=models.TextField(choices=[('VA', 'Vacation Homes'), ('EX', 'Excursion'), ('Ann', 'Anniversary'), ('Co', 'Corporate')], default='VA', max_length=1),
        ),
    ]
