# Generated by Django 2.1 on 2019-11-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_projectspage_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderinfo',
            old_name='Page',
            new_name='page',
        ),
    ]
